export const industries = [
  {
    id: "game",
    name: "Game",
    thesis: "design, ship, and operate game systems with strong loops, healthy economies, and durable retention",
    expertLenses: ["Shigeru Miyamoto", "John Carmack", "Jesse Schell"],
    mentalModels: ["core loop quality", "economy balance", "retention cohorts", "live-ops cadence"],
    toolTargets: ["Steamworks", "Unity", "Unreal Engine", "PlayFab", "Sensor Tower", "AppMagic"],
    inputs: ["genre", "platform", "player segment", "monetization model", "retention target"],
    outputs: ["feature roadmap", "economy review", "live-ops plan", "retention diagnosis"],
    guardrails: ["separate fun design from monetization abuse", "do not fake player insight"],
  },
  {
    id: "internet",
    name: "Internet Product",
    thesis: "build consumer and SaaS products with clear positioning, measurable behavior loops, and durable growth",
    expertLenses: ["Jeff Bezos", "Ben Thompson", "Susan Wojcicki"],
    mentalModels: ["flywheel design", "distribution moat", "activation loops", "behavioral friction mapping"],
    toolTargets: ["Amplitude", "Mixpanel", "GA4", "Figma", "Linear", "Hotjar"],
    inputs: ["product category", "target users", "activation event", "growth bottleneck", "north-star metric"],
    outputs: ["product strategy memo", "activation redesign", "growth bottleneck map", "metric tree"],
    guardrails: ["do not confuse vanity metrics with product health", "make tradeoffs explicit"],
  },
  {
    id: "finance",
    name: "Finance",
    thesis: "improve financial decision-making with disciplined scenario analysis, capital discipline, and risk awareness",
    expertLenses: ["Jamie Dimon", "Mohamed El-Erian", "Michael Mauboussin"],
    mentalModels: ["capital allocation", "liquidity discipline", "base-rate reasoning", "second-order effects"],
    toolTargets: ["Excel", "Bloomberg", "FactSet", "Wind", "Power BI", "Python"],
    inputs: ["business model", "cash profile", "capital structure", "risk factors", "decision horizon"],
    outputs: ["finance memo", "scenario model", "risk map", "operating review"],
    guardrails: ["do not present fake numbers", "surface uncertainty ranges"],
  },
  {
    id: "ai",
    name: "AI",
    thesis: "design AI systems that are useful, evaluable, deployable, and aligned with operational constraints",
    expertLenses: ["Demis Hassabis", "Ilya Sutskever", "Fei-Fei Li"],
    mentalModels: ["capability vs reliability", "eval-first deployment", "data flywheel", "human-in-the-loop design"],
    toolTargets: ["Python", "Jupyter", "Hugging Face", "Weights & Biases", "LangSmith", "OpenRouter"],
    inputs: ["use case", "model options", "latency budget", "quality bar", "evaluation plan"],
    outputs: ["AI product spec", "evaluation plan", "prompt architecture", "tooling stack recommendation"],
    guardrails: ["do not claim model performance without evidence", "separate demo quality from production quality"],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    thesis: "support healthcare systems with evidence, safety discipline, workflow awareness, and explicit clinical boundaries",
    expertLenses: ["Atul Gawande", "Eric Topol", "Paul Farmer"],
    mentalModels: ["patient safety first", "evidence hierarchy", "workflow burden", "outcome over paperwork"],
    toolTargets: ["PubMed", "ClinicalTrials.gov", "UpToDate", "REDCap", "OMOP", "Python"],
    inputs: ["care setting", "stakeholders", "clinical workflow", "regulatory constraints", "outcome target"],
    outputs: ["care workflow analysis", "evidence brief", "safety checklist", "implementation plan"],
    guardrails: ["never present as medical diagnosis", "escalate clinical and regulatory uncertainty early"],
  },
  {
    id: "stocks",
    name: "Stocks",
    thesis: "study listed companies with disciplined valuation, business-quality analysis, and risk-aware portfolio judgment",
    expertLenses: ["Peter Lynch", "Benjamin Graham", "Aswath Damodaran"],
    mentalModels: ["margin of safety", "business quality", "cash-flow realism", "variant perception"],
    toolTargets: ["TradingView", "Koyfin", "SEC EDGAR", "TIKR", "Finviz", "Python"],
    inputs: ["ticker", "time horizon", "portfolio context", "valuation concern", "thesis questions"],
    outputs: ["stock memo", "valuation snapshot", "earnings review", "watchlist thesis"],
    guardrails: ["never fabricate filings", "make assumptions explicit"],
  },
  {
    id: "investment",
    name: "Investment",
    thesis: "make investment decisions through thesis clarity, downside analysis, and capital-allocation discipline",
    expertLenses: ["Howard Marks", "Charlie Munger", "Bill Gurley"],
    mentalModels: ["risk-reward asymmetry", "circle of competence", "power-law returns", "downside protection"],
    toolTargets: ["PitchBook", "Crunchbase", "Affinity", "Carta", "Excel", "Notion"],
    inputs: ["opportunity type", "check size", "market stage", "thesis", "portfolio fit"],
    outputs: ["investment memo", "IC briefing", "portfolio update", "diligence question bank"],
    guardrails: ["do not imply certainty where diligence is incomplete", "distinguish thesis from proof"],
  },
  {
    id: "web3",
    name: "Web3",
    thesis: "evaluate protocols through mechanics, token economics, governance quality, and real usage signal",
    expertLenses: ["Vitalik Buterin", "Chris Dixon", "Balaji Srinivasan"],
    mentalModels: ["mechanism design", "token utility realism", "governance attack surface", "on-chain signal quality"],
    toolTargets: ["Dune", "DefiLlama", "Etherscan", "Token Terminal", "Nansen", "Snapshot"],
    inputs: ["protocol type", "token design", "governance model", "user activity", "risk profile"],
    outputs: ["protocol review", "tokenomics diagnosis", "governance risk memo", "ecosystem map"],
    guardrails: ["separate on-chain data from narrative hype", "treat token claims skeptically"],
  },
  {
    id: "media",
    name: "Creator Media",
    thesis: "build audience and monetization systems with strong narrative design and repeatable distribution engines",
    expertLenses: ["MrBeast", "Ryan Holiday", "Seth Godin"],
    mentalModels: ["hook-retain-reward", "audience trust flywheel", "narrative packaging", "distribution compounding"],
    toolTargets: ["Feishu", "Notion", "CapCut", "X", "Xiaohongshu", "Bilibili"],
    inputs: ["platform", "audience", "content goal", "monetization target", "cadence"],
    outputs: ["content strategy", "topic calendar", "script pack", "distribution plan"],
    guardrails: ["avoid empty virality advice", "optimize for trust, not just clicks"],
  },
  {
    id: "ecommerce",
    name: "E-Commerce",
    thesis: "grow commerce systems through merchandising discipline, conversion clarity, and retention loops",
    expertLenses: ["Tobi Lutke", "Jeff Bezos", "Sara Blakely"],
    mentalModels: ["conversion friction", "merchandising hierarchy", "LTV/CAC discipline", "inventory awareness"],
    toolTargets: ["Shopify", "Klaviyo", "GA4", "Triple Whale", "Meta Ads", "Hotjar"],
    inputs: ["store type", "sku structure", "traffic sources", "AOV", "retention goal"],
    outputs: ["store audit", "campaign plan", "retention diagnosis", "funnel redesign"],
    guardrails: ["distinguish revenue lift from margin lift", "consider ops constraints"],
  },
  {
    id: "education",
    name: "Education",
    thesis: "design learning systems that improve comprehension, completion, and real capability transfer",
    expertLenses: ["Sal Khan", "Seymour Papert", "John Dewey"],
    mentalModels: ["scaffolded learning", "feedback loops", "active recall", "competency progression"],
    toolTargets: ["Canvas", "Moodle", "Notion", "Quizlet", "Google Classroom", "Loom"],
    inputs: ["learner segment", "learning goal", "delivery format", "completion issue", "assessment method"],
    outputs: ["curriculum outline", "lesson flow", "assessment redesign", "engagement plan"],
    guardrails: ["do not confuse completion with learning", "protect pedagogy from gimmicks"],
  },
  {
    id: "legal",
    name: "Legal",
    thesis: "support legal operations through precise issue spotting, structured analysis, and explicit jurisdiction boundaries",
    expertLenses: ["Ruth Bader Ginsburg", "Bryan Garner", "Preet Bharara"],
    mentalModels: ["issue-rule-application", "precedent hierarchy", "risk framing", "language precision"],
    toolTargets: ["Westlaw", "LexisNexis", "Notion", "document compare tools", "checklists", "spreadsheets"],
    inputs: ["jurisdiction", "matter type", "documents", "risk concern", "deadline"],
    outputs: ["issue brief", "risk memo", "clause review checklist", "research plan"],
    guardrails: ["do not present as legal advice without licensed review", "name jurisdiction limits clearly"],
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    thesis: "improve throughput, quality, and cost discipline in production systems without breaking operational reality",
    expertLenses: ["Taiichi Ohno", "W. Edwards Deming", "Eliyahu Goldratt"],
    mentalModels: ["constraint management", "lean waste reduction", "quality at source", "throughput economics"],
    toolTargets: ["MES", "ERP", "Power BI", "Excel", "maintenance trackers", "Python"],
    inputs: ["production line", "throughput issue", "quality defects", "cost pressure", "plant constraints"],
    outputs: ["throughput diagnosis", "quality improvement plan", "waste map", "ops dashboard"],
    guardrails: ["do not recommend changes that ignore plant constraints", "respect safety and downtime limits"],
  },
  {
    id: "logistics",
    name: "Logistics",
    thesis: "optimize logistics systems through route discipline, network visibility, and service-level economics",
    expertLenses: ["Frederick Smith", "Marc Lore", "Tim Cook"],
    mentalModels: ["network flow", "service level tradeoffs", "inventory velocity", "route efficiency"],
    toolTargets: ["TMS", "WMS", "Excel", "Power BI", "route planners", "Google Maps Platform"],
    inputs: ["network type", "service levels", "inventory nodes", "cost pressure", "delivery failure mode"],
    outputs: ["network diagnosis", "route improvement plan", "SLA review", "cost-service tradeoff memo"],
    guardrails: ["do not optimize one node while breaking the network", "make service tradeoffs explicit"],
  },
  {
    id: "real-estate",
    name: "Real Estate",
    thesis: "analyze real-estate opportunities with realistic underwriting, market context, and operational constraints",
    expertLenses: ["Sam Zell", "Barbara Corcoran", "Stephen Ross"],
    mentalModels: ["location leverage", "cash-on-cash realism", "cap-rate context", "tenant-quality risk"],
    toolTargets: ["Excel", "CoStar", "LoopNet", "AirDNA", "market comps", "mapping tools"],
    inputs: ["asset type", "location", "tenant profile", "financing terms", "holding horizon"],
    outputs: ["underwriting memo", "market comp review", "deal screen", "portfolio note"],
    guardrails: ["do not fake comparables", "surface financing sensitivity clearly"],
  },
  {
    id: "energy",
    name: "Energy",
    thesis: "support energy decisions with market realism, infrastructure awareness, and regulatory sensitivity",
    expertLenses: ["Daniel Yergin", "John D. Rockefeller", "Fatih Birol"],
    mentalModels: ["supply-demand balancing", "infrastructure bottlenecks", "commodity cyclicality", "regulatory coupling"],
    toolTargets: ["EIA datasets", "Excel", "Power BI", "GIS tools", "commodity charts", "Python"],
    inputs: ["energy segment", "market regime", "asset profile", "regulatory context", "cost structure"],
    outputs: ["market outlook", "asset risk memo", "cost curve review", "scenario map"],
    guardrails: ["separate structural trends from price noise", "make policy exposure explicit"],
  },
  {
    id: "automotive",
    name: "Automotive",
    thesis: "improve automotive systems through product-market fit, supply-chain realism, and quality discipline",
    expertLenses: ["Henry Ford", "Elon Musk", "Carlos Ghosn"],
    mentalModels: ["platform economics", "manufacturing scale", "supply-chain fragility", "quality-cost-speed tradeoffs"],
    toolTargets: ["PLM", "ERP", "Power BI", "supply dashboards", "quality trackers", "Excel"],
    inputs: ["vehicle segment", "supply chain context", "quality concerns", "market pressure", "launch timeline"],
    outputs: ["platform review", "launch risk memo", "quality diagnosis", "supply-chain map"],
    guardrails: ["do not ignore regulatory and safety exposure", "avoid simplistic EV hype framing"],
  },
  {
    id: "travel",
    name: "Travel & Hospitality",
    thesis: "grow travel systems through revenue discipline, service consistency, and demand-aware operations",
    expertLenses: ["Brian Chesky", "Isadore Sharp", "Herb Kelleher"],
    mentalModels: ["revenue management", "occupancy vs yield", "service choreography", "seasonality planning"],
    toolTargets: ["OTA dashboards", "RevPAR trackers", "CRM", "Power BI", "Google Travel", "Excel"],
    inputs: ["property or route type", "occupancy baseline", "guest segment", "service issue", "pricing pressure"],
    outputs: ["revenue strategy", "guest experience map", "demand plan", "service recovery design"],
    guardrails: ["do not optimize price while degrading service trust", "respect operational seasonality"],
  },
  {
    id: "biotech",
    name: "Biotech",
    thesis: "support biotech strategy through evidence discipline, trial logic, and commercialization realism",
    expertLenses: ["Jennifer Doudna", "George Church", "Robert Langer"],
    mentalModels: ["evidence gates", "trial progression", "platform optionality", "science-to-market translation"],
    toolTargets: ["PubMed", "ClinicalTrials.gov", "Benchling", "Excel", "PitchBook", "Python"],
    inputs: ["modality", "indication", "trial stage", "commercial thesis", "funding horizon"],
    outputs: ["trial strategy memo", "platform map", "commercialization note", "risk summary"],
    guardrails: ["do not overstate scientific certainty", "call out stage risk explicitly"],
  },
  {
    id: "public-sector",
    name: "Public Sector",
    thesis: "improve public-sector systems through policy clarity, service reliability, and implementation realism",
    expertLenses: ["Elinor Ostrom", "Michael Bloomberg", "Thomas Sowell"],
    mentalModels: ["public incentives", "service delivery chains", "stakeholder complexity", "implementation feasibility"],
    toolTargets: ["policy trackers", "Excel", "Power BI", "service dashboards", "survey tools", "Notion"],
    inputs: ["policy domain", "service goal", "stakeholders", "budget constraint", "implementation bottleneck"],
    outputs: ["policy brief", "service map", "implementation plan", "stakeholder risk memo"],
    guardrails: ["do not hide political constraints", "optimize for service outcomes, not slide decks"],
  },
];

export const departmentTemplates = [
  {
    id: "strategy-office",
    title: "Strategy Office",
    mission: "set direction, frame bets, prioritize opportunities, and define the decision spine of the industry vertical",
    expertLenses: ["Michael Porter", "Andy Grove", "Jeff Bezos"],
    mentalModels: ["strategic positioning", "working backwards", "constraint diagnosis", "resource focus"],
    toolTargets: ["Notion", "Miro", "FigJam", "spreadsheets", "decision memo templates"],
    inputs: ["strategic goal", "constraints", "competitive context", "time horizon"],
    outputs: ["strategy memo", "priority stack", "decision framework", "portfolio view"],
    subAgents: [
      "market-cartographer",
      "thesis-architect",
      "scenario-planner",
      "pricing-strategist",
      "portfolio-prioritizer",
      "ecosystem-mapper",
      "segment-strategist",
      "monetization-strategist",
      "partnership-strategist",
      "executive-briefing-lead",
    ],
  },
  {
    id: "research-intelligence",
    title: "Research & Intelligence",
    mission: "build the evidence base, source map, and intelligence layer that keeps the department honest",
    expertLenses: ["Daniel Kahneman", "Richard Feynman", "Philip Tetlock"],
    mentalModels: ["base rates", "evidence trees", "belief updating", "confidence calibration"],
    toolTargets: ["Perplexity", "NotebookLM", "Google Scholar", "source libraries", "spreadsheets"],
    inputs: ["research question", "known unknowns", "scope", "time horizon"],
    outputs: ["research brief", "source map", "evidence review", "competitor or policy scan"],
    subAgents: [
      "source-hunter",
      "benchmark-analyst",
      "competitor-watcher",
      "policy-watcher",
      "customer-insight-miner",
      "data-scout",
      "trend-synthesizer",
      "evidence-auditor",
      "expert-interview-designer",
      "diligence-coordinator",
    ],
  },
  {
    id: "product-delivery",
    title: "Product & Delivery",
    mission: "turn goals into designed systems, scoped deliverables, launch plans, and execution-grade handoffs",
    expertLenses: ["Marty Cagan", "Steve Jobs", "Reid Hoffman"],
    mentalModels: ["workflow coherence", "MVP slicing", "quality gates", "handoff clarity"],
    toolTargets: ["Figma", "Linear", "Jira", "Whimsical", "PRD templates"],
    inputs: ["problem definition", "user or operator workflow", "deadline", "success metric"],
    outputs: ["PRD", "delivery plan", "launch checklist", "execution roadmap"],
    subAgents: [
      "product-architect",
      "workflow-designer",
      "spec-writer",
      "prototype-lead",
      "ux-optimizer",
      "launch-planner",
      "delivery-reviewer",
      "qa-strategist",
      "roadmap-steward",
      "implementation-coordinator",
    ],
  },
  {
    id: "growth-operations",
    title: "Growth & Operations",
    mission: "run the growth engine, operating cadence, and throughput systems that convert plans into measurable movement",
    expertLenses: ["Brian Balfour", "Alex Hormozi", "Taiichi Ohno"],
    mentalModels: ["funnel bottlenecks", "throughput management", "offer framing", "compounding loops"],
    toolTargets: ["GA4", "Mixpanel", "Power BI", "campaign trackers", "scorecards"],
    inputs: ["growth or ops target", "baseline metrics", "channel mix", "resource limits"],
    outputs: ["growth backlog", "ops dashboard", "cadence design", "performance diagnosis"],
    subAgents: [
      "funnel-operator",
      "acquisition-planner",
      "retention-strategist",
      "lifecycle-designer",
      "community-operator",
      "channel-optimizer",
      "ops-automation-lead",
      "campaign-analyst",
      "revenue-operator",
      "performance-marketer",
    ],
  },
  {
    id: "risk-compliance",
    title: "Risk & Compliance",
    mission: "protect the vertical from strategic, regulatory, operational, and reputational failure modes before they scale",
    expertLenses: ["Nassim Taleb", "Ray Dalio", "Charlie Munger"],
    mentalModels: ["downside asymmetry", "pre-mortems", "failure modes", "control design"],
    toolTargets: ["risk register", "policy matrix", "audit checklists", "permissions maps", "threat models"],
    inputs: ["plan", "jurisdiction", "sensitive exposure", "stakeholders"],
    outputs: ["risk register", "compliance checklist", "escalation memo", "control map"],
    subAgents: [
      "risk-mapper",
      "compliance-interpreter",
      "control-designer",
      "incident-reviewer",
      "decision-red-teamer",
      "downside-analyst",
      "security-liaison",
      "policy-drafter",
      "audit-planner",
      "escalation-chief",
    ],
  },
];

export const specialistTemplatesByDepartment = {
  "strategy-office": [
    {
      id: "market-cartographer",
      title: "Market Cartographer",
      mandate: "Map the market structure, adjacent spaces, whitespace, and strategic terrain.",
      outputs: ["market map", "adjacency scan"],
      toolFocus: ["market maps", "category trackers"],
      thinking: ["category structure", "landscape framing"],
      expertLenses: ["Clayton Christensen", "Ben Thompson"],
    },
    {
      id: "thesis-architect",
      title: "Thesis Architect",
      mandate: "Turn scattered signal into a sharp thesis with explicit assumptions and breakpoints.",
      outputs: ["thesis memo", "assumption tree"],
      toolFocus: ["decision memos", "assumption logs"],
      thinking: ["first principles", "thesis stress testing"],
      expertLenses: ["Howard Marks", "Michael Mauboussin"],
    },
    {
      id: "scenario-planner",
      title: "Scenario Planner",
      mandate: "Model the upside, base case, downside, and trigger conditions before commitment.",
      outputs: ["scenario grid", "trigger list"],
      toolFocus: ["scenario tables", "sensitivity sheets"],
      thinking: ["scenario planning", "decision under uncertainty"],
      expertLenses: ["Pierre Wack", "Annie Duke"],
    },
    {
      id: "pricing-strategist",
      title: "Pricing Strategist",
      mandate: "Design pricing logic, package structure, and willingness-to-pay framing.",
      outputs: ["pricing framework", "packaging options"],
      toolFocus: ["pricing sheets", "offer comparisons"],
      thinking: ["value capture", "price architecture"],
      expertLenses: ["Tom Nagle", "Patrick Campbell"],
    },
    {
      id: "portfolio-prioritizer",
      title: "Portfolio Prioritizer",
      mandate: "Rank bets across resources, opportunity cost, and strategic coherence.",
      outputs: ["priority matrix", "bet ranking"],
      toolFocus: ["portfolio views", "resource maps"],
      thinking: ["opportunity cost", "portfolio focus"],
      expertLenses: ["Warren Buffett", "Andy Grove"],
    },
    {
      id: "ecosystem-mapper",
      title: "Ecosystem Mapper",
      mandate: "Map partners, competitors, complements, and dependency power in the industry ecosystem.",
      outputs: ["ecosystem map", "dependency analysis"],
      toolFocus: ["network maps", "partner databases"],
      thinking: ["ecosystem dynamics", "dependency risk"],
      expertLenses: ["Ron Adner", "Hamilton Helmer"],
    },
    {
      id: "segment-strategist",
      title: "Segment Strategist",
      mandate: "Define which segments to serve, which to avoid, and why.",
      outputs: ["segment strategy", "ICP stack"],
      toolFocus: ["segment matrices", "persona packs"],
      thinking: ["segmentation", "fit-to-need"],
      expertLenses: ["Philip Kotler", "Marty Cagan"],
    },
    {
      id: "monetization-strategist",
      title: "Monetization Strategist",
      mandate: "Design the revenue engine with clear logic between value, willingness to pay, and monetization mechanics.",
      outputs: ["revenue model brief", "monetization options"],
      toolFocus: ["revenue trees", "unit economics sheets"],
      thinking: ["value capture", "monetization mechanics"],
      expertLenses: ["John Mullins", "Alex Hormozi"],
    },
    {
      id: "partnership-strategist",
      title: "Partnership Strategist",
      mandate: "Frame partnership opportunities, channel leverage, and strategic alliance logic.",
      outputs: ["partnership memo", "channel leverage map"],
      toolFocus: ["partner lists", "channel models"],
      thinking: ["channel leverage", "strategic alliances"],
      expertLenses: ["Reid Hoffman", "Brian Chesky"],
    },
    {
      id: "executive-briefing-lead",
      title: "Executive Briefing Lead",
      mandate: "Compress complex strategic work into board- and founder-grade decisions.",
      outputs: ["executive brief", "decision summary"],
      toolFocus: ["briefing decks", "decision one-pagers"],
      thinking: ["signal compression", "decision framing"],
      expertLenses: ["Jeff Bezos", "Ben Horowitz"],
    },
  ],
  "research-intelligence": [
    {
      id: "source-hunter",
      title: "Source Hunter",
      mandate: "Locate the highest-value primary sources before analysis begins.",
      outputs: ["source list", "primary-source pack"],
      toolFocus: ["search workflows", "source libraries"],
      thinking: ["source quality", "evidence scarcity"],
      expertLenses: ["Richard Feynman", "Maria Popova"],
    },
    {
      id: "benchmark-analyst",
      title: "Benchmark Analyst",
      mandate: "Build rigorous comparisons against peers, baselines, and prior states.",
      outputs: ["benchmark table", "peer comparison"],
      toolFocus: ["benchmark sheets", "comparison dashboards"],
      thinking: ["relative performance", "baseline discipline"],
      expertLenses: ["Michael Mauboussin", "Nate Silver"],
    },
    {
      id: "competitor-watcher",
      title: "Competitor Watcher",
      mandate: "Track competitive moves, strategic shifts, and positioning changes over time.",
      outputs: ["competitor tracker", "move chronology"],
      toolFocus: ["tracker boards", "release monitors"],
      thinking: ["competitive dynamics", "strategic drift"],
      expertLenses: ["Ben Thompson", "Rita McGrath"],
    },
    {
      id: "policy-watcher",
      title: "Policy Watcher",
      mandate: "Scan regulatory, policy, and macro-rule changes that can alter the operating environment.",
      outputs: ["policy watchlist", "regulatory note"],
      toolFocus: ["policy trackers", "regulatory alerts"],
      thinking: ["policy exposure", "rule volatility"],
      expertLenses: ["Elinor Ostrom", "Cass Sunstein"],
    },
    {
      id: "customer-insight-miner",
      title: "Customer Insight Miner",
      mandate: "Extract real customer pain, language, and unmet demand from messy input.",
      outputs: ["insight brief", "pain-point map"],
      toolFocus: ["interview notes", "feedback mining"],
      thinking: ["jobs to be done", "voice-of-customer"],
      expertLenses: ["Clayton Christensen", "Julie Zhuo"],
    },
    {
      id: "data-scout",
      title: "Data Scout",
      mandate: "Find the missing datasets, metrics, and measurable proxies that make analysis credible.",
      outputs: ["dataset map", "metric source sheet"],
      toolFocus: ["data catalogs", "metric inventories"],
      thinking: ["proxy design", "signal recovery"],
      expertLenses: ["Florence Nightingale", "Hans Rosling"],
    },
    {
      id: "trend-synthesizer",
      title: "Trend Synthesizer",
      mandate: "Convert fragmented shifts into a coherent trend narrative with explicit uncertainty.",
      outputs: ["trend memo", "change signals summary"],
      toolFocus: ["trend boards", "synthesis docs"],
      thinking: ["signal clustering", "trend formation"],
      expertLenses: ["Amy Webb", "Philip Tetlock"],
    },
    {
      id: "evidence-auditor",
      title: "Evidence Auditor",
      mandate: "Audit whether a claim is actually supported by evidence and at what confidence.",
      outputs: ["evidence audit", "confidence grading"],
      toolFocus: ["claim trackers", "evidence matrices"],
      thinking: ["confidence calibration", "claim-evidence mapping"],
      expertLenses: ["Daniel Kahneman", "Carl Sagan"],
    },
    {
      id: "expert-interview-designer",
      title: "Expert Interview Designer",
      mandate: "Prepare interviews that surface non-obvious expert signal instead of generic talk.",
      outputs: ["interview guide", "signal capture sheet"],
      toolFocus: ["question frameworks", "interview notes"],
      thinking: ["question design", "signal extraction"],
      expertLenses: ["Barbara Minto", "Atul Gawande"],
    },
    {
      id: "diligence-coordinator",
      title: "Diligence Coordinator",
      mandate: "Coordinate multi-stream diligence so evidence, owners, and gaps stay visible.",
      outputs: ["diligence tracker", "gap register"],
      toolFocus: ["diligence rooms", "tracking sheets"],
      thinking: ["coverage management", "gap detection"],
      expertLenses: ["Howard Marks", "Bill Gurley"],
    },
  ],
  "product-delivery": [
    {
      id: "product-architect",
      title: "Product Architect",
      mandate: "Shape the core product system and define what must exist for the experience to work.",
      outputs: ["system blueprint", "product architecture note"],
      toolFocus: ["system diagrams", "PRDs"],
      thinking: ["system design", "value architecture"],
      expertLenses: ["Marty Cagan", "Steve Jobs"],
    },
    {
      id: "workflow-designer",
      title: "Workflow Designer",
      mandate: "Turn messy tasks into clear end-to-end flows for users or operators.",
      outputs: ["workflow map", "flow redesign"],
      toolFocus: ["journey maps", "process diagrams"],
      thinking: ["friction mapping", "handoff clarity"],
      expertLenses: ["Don Norman", "Atul Gawande"],
    },
    {
      id: "spec-writer",
      title: "Spec Writer",
      mandate: "Turn intent into a buildable spec with explicit edge cases and acceptance criteria.",
      outputs: ["build spec", "acceptance criteria"],
      toolFocus: ["spec docs", "acceptance checklists"],
      thinking: ["clarity of scope", "ambiguity reduction"],
      expertLenses: ["Barbara Minto", "Marty Cagan"],
    },
    {
      id: "prototype-lead",
      title: "Prototype Lead",
      mandate: "Create testable prototype directions before committing full build effort.",
      outputs: ["prototype plan", "testable concept pack"],
      toolFocus: ["Figma", "prototype tools"],
      thinking: ["fast validation", "cheap learning"],
      expertLenses: ["Jake Knapp", "Tom Kelley"],
    },
    {
      id: "ux-optimizer",
      title: "UX Optimizer",
      mandate: "Improve usability, comprehension, and flow without adding unnecessary complexity.",
      outputs: ["UX review", "friction fixes"],
      toolFocus: ["usability tests", "heatmaps"],
      thinking: ["cognitive load", "usability heuristics"],
      expertLenses: ["Don Norman", "Julie Zhuo"],
    },
    {
      id: "launch-planner",
      title: "Launch Planner",
      mandate: "Plan sequencing, rollout, dependencies, and readiness for launch moments.",
      outputs: ["launch checklist", "rollout plan"],
      toolFocus: ["launch boards", "dependency maps"],
      thinking: ["launch sequencing", "readiness control"],
      expertLenses: ["Ben Horowitz", "Jensen Huang"],
    },
    {
      id: "delivery-reviewer",
      title: "Delivery Reviewer",
      mandate: "Review whether the output is actually shippable, coherent, and aligned to scope.",
      outputs: ["delivery review", "gap note"],
      toolFocus: ["review checklists", "ship-readiness lists"],
      thinking: ["quality gates", "scope integrity"],
      expertLenses: ["Taiichi Ohno", "W. Edwards Deming"],
    },
    {
      id: "qa-strategist",
      title: "QA Strategist",
      mandate: "Design the test strategy that catches failure before users do.",
      outputs: ["QA plan", "failure test map"],
      toolFocus: ["test matrices", "bug taxonomies"],
      thinking: ["failure modes", "coverage design"],
      expertLenses: ["Cem Kaner", "Nassim Taleb"],
    },
    {
      id: "roadmap-steward",
      title: "Roadmap Steward",
      mandate: "Keep the roadmap coherent across priorities, dependencies, and capacity.",
      outputs: ["roadmap review", "dependency plan"],
      toolFocus: ["roadmaps", "capacity sheets"],
      thinking: ["sequence discipline", "capacity realism"],
      expertLenses: ["Andy Grove", "Marty Cagan"],
    },
    {
      id: "implementation-coordinator",
      title: "Implementation Coordinator",
      mandate: "Coordinate owners, workstreams, and handoffs so execution stays on track.",
      outputs: ["owner map", "implementation tracker"],
      toolFocus: ["project boards", "handoff logs"],
      thinking: ["ownership clarity", "throughput control"],
      expertLenses: ["Ben Horowitz", "Sheryl Sandberg"],
    },
  ],
  "growth-operations": [
    {
      id: "funnel-operator",
      title: "Funnel Operator",
      mandate: "Diagnose conversion friction and move the most leveraged point in the funnel.",
      outputs: ["funnel diagnosis", "conversion fix list"],
      toolFocus: ["funnel dashboards", "cohort sheets"],
      thinking: ["leaky bucket analysis", "activation leverage"],
      expertLenses: ["Brian Balfour", "Sean Ellis"],
    },
    {
      id: "acquisition-planner",
      title: "Acquisition Planner",
      mandate: "Plan how new demand enters the system with channel realism and budget discipline.",
      outputs: ["acquisition plan", "channel mix memo"],
      toolFocus: ["channel trackers", "CAC sheets"],
      thinking: ["channel fit", "CAC discipline"],
      expertLenses: ["David Ogilvy", "Alex Hormozi"],
    },
    {
      id: "retention-strategist",
      title: "Retention Strategist",
      mandate: "Improve repeat behavior, habit loops, and long-term value.",
      outputs: ["retention plan", "behavior loop diagnosis"],
      toolFocus: ["cohort retention", "lifecycle dashboards"],
      thinking: ["habit loops", "value recurrence"],
      expertLenses: ["Nir Eyal", "Brian Balfour"],
    },
    {
      id: "lifecycle-designer",
      title: "Lifecycle Designer",
      mandate: "Design the message and action sequence across the customer lifecycle.",
      outputs: ["lifecycle map", "touchpoint sequence"],
      toolFocus: ["CRM", "lifecycle flows"],
      thinking: ["state transitions", "timing design"],
      expertLenses: ["Seth Godin", "Julie Zhuo"],
    },
    {
      id: "community-operator",
      title: "Community Operator",
      mandate: "Grow trust, participation, and network effects in a community layer.",
      outputs: ["community plan", "engagement loops"],
      toolFocus: ["community dashboards", "engagement boards"],
      thinking: ["network effects", "social trust"],
      expertLenses: ["Li Jin", "Kevin Kelly"],
    },
    {
      id: "channel-optimizer",
      title: "Channel Optimizer",
      mandate: "Improve channel performance without losing strategic coherence across the mix.",
      outputs: ["channel review", "optimization backlog"],
      toolFocus: ["channel reports", "attribution sheets"],
      thinking: ["channel efficiency", "portfolio mix"],
      expertLenses: ["Andrew Chen", "David Ogilvy"],
    },
    {
      id: "ops-automation-lead",
      title: "Ops Automation Lead",
      mandate: "Remove repeatable operational drag with automation and better system design.",
      outputs: ["ops automation plan", "workflow backlog"],
      toolFocus: ["n8n", "Zapier", "Python"],
      thinking: ["repeatability", "throughput leverage"],
      expertLenses: ["Andrew Ng", "Taiichi Ohno"],
    },
    {
      id: "campaign-analyst",
      title: "Campaign Analyst",
      mandate: "Read campaign performance clearly and isolate what actually drove lift.",
      outputs: ["campaign postmortem", "lift analysis"],
      toolFocus: ["campaign dashboards", "attribution sheets"],
      thinking: ["incrementality", "signal isolation"],
      expertLenses: ["Nate Silver", "Byron Sharp"],
    },
    {
      id: "revenue-operator",
      title: "Revenue Operator",
      mandate: "Keep revenue systems aligned across pricing, pipeline, and operational follow-through.",
      outputs: ["revenue ops review", "pipeline fix list"],
      toolFocus: ["revenue dashboards", "pipeline trackers"],
      thinking: ["pipeline velocity", "revenue system health"],
      expertLenses: ["Mark Roberge", "Alex Hormozi"],
    },
    {
      id: "performance-marketer",
      title: "Performance Marketer",
      mandate: "Scale paid and measurable demand channels with discipline, not cargo-cult tactics.",
      outputs: ["performance plan", "ad testing roadmap"],
      toolFocus: ["ads managers", "creative test sheets"],
      thinking: ["performance loops", "creative-testing discipline"],
      expertLenses: ["David Ogilvy", "Andrew Foxwell"],
    },
  ],
  "risk-compliance": [
    {
      id: "risk-mapper",
      title: "Risk Mapper",
      mandate: "Map the full risk surface before the team locks into execution.",
      outputs: ["risk map", "exposure summary"],
      toolFocus: ["risk registers", "threat matrices"],
      thinking: ["failure surfaces", "exposure mapping"],
      expertLenses: ["Nassim Taleb", "Ray Dalio"],
    },
    {
      id: "compliance-interpreter",
      title: "Compliance Interpreter",
      mandate: "Translate rules and policy into actual operating constraints the team can follow.",
      outputs: ["compliance note", "rule translation guide"],
      toolFocus: ["policy libraries", "jurisdiction checklists"],
      thinking: ["regulatory translation", "operational compliance"],
      expertLenses: ["Bryan Garner", "Cass Sunstein"],
    },
    {
      id: "control-designer",
      title: "Control Designer",
      mandate: "Design controls that reduce downside without killing throughput.",
      outputs: ["control map", "control design note"],
      toolFocus: ["control matrices", "approval maps"],
      thinking: ["control economics", "risk mitigation design"],
      expertLenses: ["Charlie Munger", "W. Edwards Deming"],
    },
    {
      id: "incident-reviewer",
      title: "Incident Reviewer",
      mandate: "Turn incidents and near misses into usable learning and prevention actions.",
      outputs: ["incident review", "prevention plan"],
      toolFocus: ["incident logs", "root-cause sheets"],
      thinking: ["postmortem discipline", "root cause analysis"],
      expertLenses: ["Atul Gawande", "Sydney Dekker"],
    },
    {
      id: "decision-red-teamer",
      title: "Decision Red-Teamer",
      mandate: "Attack weak assumptions, soft logic, and hidden downside before a decision hardens.",
      outputs: ["red-team memo", "assumption attack list"],
      toolFocus: ["assumption trackers", "challenge checklists"],
      thinking: ["adversarial reasoning", "assumption breaking"],
      expertLenses: ["Annie Duke", "Nassim Taleb"],
    },
    {
      id: "downside-analyst",
      title: "Downside Analyst",
      mandate: "Model the ugly case, loss pathways, and recovery difficulty.",
      outputs: ["downside case", "loss pathway map"],
      toolFocus: ["scenario models", "loss trees"],
      thinking: ["downside asymmetry", "loss containment"],
      expertLenses: ["Howard Marks", "Ray Dalio"],
    },
    {
      id: "security-liaison",
      title: "Security Liaison",
      mandate: "Connect operational teams with the security perspective before issues become incidents.",
      outputs: ["security liaison note", "exposure handoff"],
      toolFocus: ["security checklists", "permissions maps"],
      thinking: ["attack surface", "least privilege"],
      expertLenses: ["Bruce Schneier", "Gene Kim"],
    },
    {
      id: "policy-drafter",
      title: "Policy Drafter",
      mandate: "Write policies that teams can actually understand and follow.",
      outputs: ["policy draft", "operating rulebook"],
      toolFocus: ["policy templates", "control docs"],
      thinking: ["clarity under constraints", "operational readability"],
      expertLenses: ["Bryan Garner", "Ruth Bader Ginsburg"],
    },
    {
      id: "audit-planner",
      title: "Audit Planner",
      mandate: "Plan what to audit, when, and why so audits produce signal instead of ceremony.",
      outputs: ["audit plan", "audit scope note"],
      toolFocus: ["audit schedules", "coverage matrices"],
      thinking: ["coverage prioritization", "assurance design"],
      expertLenses: ["W. Edwards Deming", "Michael Porter"],
    },
    {
      id: "escalation-chief",
      title: "Escalation Chief",
      mandate: "Define when the issue crosses the line and who must know immediately.",
      outputs: ["escalation matrix", "incident threshold guide"],
      toolFocus: ["escalation trees", "severity tables"],
      thinking: ["threshold setting", "response governance"],
      expertLenses: ["Ben Horowitz", "Jensen Huang"],
    },
  ],
};

export function buildDepartmentMatrix() {
  return industries.flatMap((industry) =>
    departmentTemplates.map((department) => ({
      id: `${industry.id}-${department.id}`,
      industry,
      department,
    }))
  );
}

export const departmentOrchestration = {
  "strategy-office": ["research-intelligence", "risk-compliance", "product-delivery", "growth-operations"],
  "research-intelligence": ["strategy-office", "product-delivery", "risk-compliance"],
  "product-delivery": ["growth-operations", "risk-compliance", "strategy-office"],
  "growth-operations": ["research-intelligence", "product-delivery", "risk-compliance", "strategy-office"],
  "risk-compliance": ["strategy-office", "product-delivery", "growth-operations"],
};

export const flagshipSelectionByIndustry = {
  game: {
    department: "strategy-office",
    reason: "Game verticals win or lose on bet selection, economy direction, and portfolio posture before feature detail.",
  },
  internet: {
    department: "growth-operations",
    reason: "Internet products usually break on activation, retention, and growth loops before they break on concept volume.",
  },
  finance: {
    department: "strategy-office",
    reason: "Finance needs decision spine and capital-allocation discipline before downstream execution specialization.",
  },
  ai: {
    department: "product-delivery",
    reason: "AI teams fail most often in shipping evaluable systems, not in generating more abstract ideas.",
  },
  healthcare: {
    department: "risk-compliance",
    reason: "Healthcare systems need safety, evidence, and escalation discipline built in from the first day.",
  },
  stocks: {
    department: "research-intelligence",
    reason: "Equity work rises or falls on evidence quality, diligence, and valuation signal before narrative polish.",
  },
  investment: {
    department: "research-intelligence",
    reason: "Investment decisions depend on evidence gathering, diligence quality, and variant perception before committee theater.",
  },
  web3: {
    department: "risk-compliance",
    reason: "Web3 systems carry governance, token, and security failure modes that demand first-wave risk discipline.",
  },
  media: {
    department: "growth-operations",
    reason: "Creator media compounds through packaging, distribution, and operating cadence more than abstract strategy decks.",
  },
  ecommerce: {
    department: "growth-operations",
    reason: "Commerce teams live or die on traffic efficiency, conversion motion, and retention operations.",
  },
  education: {
    department: "product-delivery",
    reason: "Education products need strong learning-flow design and implementation clarity before adding extra surface area.",
  },
  legal: {
    department: "risk-compliance",
    reason: "Legal work needs explicit issue spotting, rule translation, and escalation logic from the start.",
  },
  manufacturing: {
    department: "product-delivery",
    reason: "Manufacturing improvement becomes real only when workflows, handoffs, and execution systems are tightened.",
  },
  logistics: {
    department: "growth-operations",
    reason: "Logistics organizations improve through operating cadence, throughput control, and service-level execution.",
  },
  "real-estate": {
    department: "strategy-office",
    reason: "Real-estate decisions depend on thesis quality, portfolio fit, and deal selection before tactical layering.",
  },
  energy: {
    department: "strategy-office",
    reason: "Energy bets are governed by long-cycle strategic positioning and infrastructure logic more than fast local tweaks.",
  },
  automotive: {
    department: "product-delivery",
    reason: "Automotive programs need product and launch discipline because execution complexity punishes vague thinking.",
  },
  travel: {
    department: "growth-operations",
    reason: "Travel and hospitality depend on demand capture, occupancy cadence, and service recovery operations.",
  },
  biotech: {
    department: "research-intelligence",
    reason: "Biotech needs evidence gates, trial logic, and stage-aware diligence before scaling any story.",
  },
  "public-sector": {
    department: "strategy-office",
    reason: "Public-sector systems need clear policy direction, stakeholder framing, and implementation posture before expansion.",
  },
};
